-- ============================================================================
--  Mudra Diamond Jobwork — Supabase schema v5.0
--  Supabase > SQL Editor માં આ આખી file એક વખત paste કરીને Run કરો.
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- entries ---
create table if not exists public.jobwork_entries (
  id          bigint generated by default as identity primary key,
  client_id   text unique not null,
  company     text not null,
  date        date,
  jangad      text,
  party       text,
  process     text,
  subprocess  text,
  pieces      numeric not null default 0,
  pending     numeric not null default 0,
  total       numeric not null default 0,
  weight      numeric not null default 0,
  rate        numeric not null default 0,
  payment     numeric not null default 0,
  status      text not null default 'Pending',
  remarks     text,
  user_name   text,
  deleted     boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- upgrades (safe to re-run)
alter table public.jobwork_entries add column if not exists deleted boolean not null default false;

-- v5.1: `payment` is the billed amount (pieces x rate) and always equals it,
-- so it could never express what a party had actually settled. `paid` holds
-- the money received; anything still owed is amount - paid.
alter table public.jobwork_entries add column if not exists paid numeric not null default 0;

-- backfill: entries marked Paid before this column existed were fully settled
update public.jobwork_entries
   set paid = payment
 where paid = 0 and status = 'Paid';

create index if not exists jobwork_company_date_idx  on public.jobwork_entries(company, date);
create index if not exists jobwork_company_party_idx on public.jobwork_entries(company, party);

-- ---------------------------------------------------------------- masters ---
create table if not exists public.parties (
  id         bigint generated by default as identity primary key,
  client_id  text unique not null,
  company    text not null,
  name       text not null,
  phone      text,
  note       text,
  deleted    boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.processes (
  id         bigint generated by default as identity primary key,
  client_id  text unique not null,
  company    text not null,
  name       text not null,
  deleted    boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.subprocesses (
  id         bigint generated by default as identity primary key,
  client_id  text unique not null,
  company    text not null,
  process    text not null,
  name       text not null,
  deleted    boolean not null default false,
  updated_at timestamptz not null default now()
);

create index if not exists parties_company_idx      on public.parties(company);
create index if not exists processes_company_idx    on public.processes(company);
create index if not exists subprocesses_company_idx on public.subprocesses(company);

-- ------------------------------------------------------------------ users ---
-- `pass` holds a salted, 5000-round SHA-256 hash — never a plaintext password.
create table if not exists public.app_users (
  id           bigint generated by default as identity primary key,
  client_id    text unique not null,
  company      text not null,
  username     text not null,
  name         text,
  role         text not null default 'viewer'
               check (role in ('admin','manager','operator','viewer')),
  pass         text not null,
  active       boolean not null default true,
  must_change  boolean not null default false,
  deleted      boolean not null default false,
  updated_at   timestamptz not null default now()
);

create unique index if not exists app_users_company_username_idx
  on public.app_users(company, username);

-- ------------------------------------------------------- updated_at helper ---
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

do $$
declare t text;
begin
  foreach t in array array['jobwork_entries','parties','processes','subprocesses','app_users']
  loop
    execute format('drop trigger if exists touch_%1$s on public.%1$I', t);
    execute format(
      'create trigger touch_%1$s before update on public.%1$I
       for each row execute function public.touch_updated_at()', t);
  end loop;
end $$;

-- ================================= SECURITY =================================
-- The app's anon key is public (it ships inside the web page and the APK), so
-- these policies are what actually protect the data. The starter policies below
-- let any holder of the anon key read/write this project's rows — fine for a
-- single-company internal tool behind a private link, NOT fine if the link or
-- key ever becomes public.
--
-- To lock it down properly later: switch the app to Supabase Auth and replace
-- `using (true)` with `using (auth.uid() is not null)`, or check a JWT claim
-- such as `auth.jwt() ->> 'company' = company`.
-- ============================================================================

alter table public.jobwork_entries enable row level security;
alter table public.parties         enable row level security;
alter table public.processes       enable row level security;
alter table public.subprocesses    enable row level security;
alter table public.app_users       enable row level security;

do $$
declare t text;
begin
  foreach t in array array['jobwork_entries','parties','processes','subprocesses','app_users']
  loop
    execute format('drop policy if exists "%1$s_select" on public.%1$I', t);
    execute format('drop policy if exists "%1$s_insert" on public.%1$I', t);
    execute format('drop policy if exists "%1$s_update" on public.%1$I', t);

    execute format('create policy "%1$s_select" on public.%1$I for select using (true)', t);
    execute format('create policy "%1$s_insert" on public.%1$I for insert with check (true)', t);
    execute format('create policy "%1$s_update" on public.%1$I for update using (true) with check (true)', t);
  end loop;
end $$;

-- Note: no DELETE policy anywhere on purpose. The app never hard-deletes —
-- it sets deleted = true, so a mistaken delete on one phone can be undone
-- and history is preserved.
